spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true


spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/spring-sns
  username: postgres
  password: postgres
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: kim_kyuhyeok_sns-application.secret_key
  token.expired-time-ms: 2592000000